{
    "id": "OSSA-20250210-5429",
    "version": "1.0.0",
    "severity": "Informational",
    "description": "Zope Event Publication (Python 3)",
    "title": "Advisory for python3-zope-event",
    "package_name": "python3-zope-event",
    "publisher": "Generated by OSSA Collector",
    "last_updated": "2025-02-10T10:52:57.892359",
    "approvals": [
        {
            "consumption": true,
            "externalization": true
        }
    ],
    "purls": [
        "pkg:rpm/amzn/python3-zope-event@4.2.0"
    ],
    "regex": [
        "^pkg:rpm/amzn/python3-zope-event.*"
    ],
    "affected_versions": [
        "*.*",
        "4.2.0"
    ],
    "artifacts": [
        {
            "url": "file://zope.event-4.2.0.tar.gz",
            "hashes": {
                "sha1": "0ee288bac481d736ad3d4a68ef23092a981cb55f",
                "sha256": "ce11004217863a4827ea1a67a31730bddab9073832bdb3b9be85869259118758",
                "ssdeep": "12288:g6Y6uV+k2UBrKFcSRojc1GhyWTGooJWNag6CLhiIa8kWb:gN6uMljGjc1GDTGogaLhiIa8kQ",
                "swhid": "swh:1:cnt:0ee288bac481d736ad3d4a68ef23092a981cb55f"
            },
            "swhid": "swh:1:dir:2b62a35a315c7e88f31e93d74017d5d92424e3ec"
        }
    ],
    "licenses": "ZPLv2.1",
    "aliases": [],
    "references": "http://pypi.python.org/pypi/zope.event/"
}